### ISSUE TITLE
Website adds decimal place to displayed balances

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#203] opened 2018-07-24 21:18 UTC
The request `memes.market/api/investor/rickles42_test` returns the following JSON:

> `{"badges":[],"balance":1000,"broke":0,"completed":0,"name":"rickles42_test","networth":1000}`

However, the user profile page for rickles42_test shows:

> net worth: 1,000 M¢
> balance: 1,000.0 M¢

I see the same behavior on the "Total balances" statistic on index.html.

**Comment by thecsw** [comment] 2018-07-24 22:43
Is this a problem?

**Comment by rickles42** [comment] 2018-07-24 23:00
What do you mean? Is this a big problem? No, it's not. But it definitely shouldn't work like this, since MemeCoins can't be fractional. So we should track it as a bug, minor though it may be, and fix it sooner or later.

**Comment by thecsw** [comment] 2018-07-24 23:40
I'm so sorry, I just misunderstood what you were saying! Sure, we can get rid of the float division by converting them to integers or casting.

**Comment by robalb** [comment] 2018-07-25 07:54
It's not a problem of type conversion (js doesn't have integers btw, only 64 bits IEEE 754 floating point). This problem is caused by a typo in the counter initialization. I'll try to fix it asap

**Comment by robalb** [comment] 2018-07-25 13:01
ok, closing this

**Closed as completed by robalb** 2018-07-25 13:01 UTC
Labels: bug
