### ISSUE TITLE
Add "!invest all" or "!allin" commands

### ISSUE THREAD

**Issue by RableJustRable** [thecsw/memeinvestor_bot#220] opened 2018-07-30 20:44 UTC
Calls that simply invest all of a users memecoins into one meme. 

As it stands now, if you dont already know your balance there is no way to invest all your memecoins without making a !balance call first. Since a lot of people invest all their meme coins into one meme this would make things easier. 

An off shoot of this would be something like "!invest all leave 200" or "!allin leave 200" which would leave 200 memecoins in your account but invest the rest of the account.

**Comment by rickles42** [comment] 2018-07-30 21:13
Hi there, thanks for the suggestion! I'm going to close this as a duplicate of Issue #75. We're currently considering adding a invest-by-percentage option that would let you do something like this.

**Closed as completed by rickles42** 2018-07-30 21:13 UTC
